<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">contains</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZUN1cnNvciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoKdHJ5IHsKCVN0
cmluZyBpbnB1dCA9IHBpcGVDdXJzb3IuZmlyc3QoImlucHV0IikgPyAoU3RyaW5nKXBpcGVDdXJz
b3IuZ2V0VmFsdWUoKSA6IG51bGw7CglTdHJpbmcgY29tcGFyZSA9IHBpcGVDdXJzb3IuZmlyc3Qo
ImNvbXBhcmUiKSA/IChTdHJpbmcpcGlwZUN1cnNvci5nZXRWYWx1ZSgpIDogbnVsbDsKCQoJU3Ry
aW5nIGluaXRUaW1lID0gVXRpbC5nZXRUaW1lU3RhbXAoKTsJCQoJUmVzdWx0IHJlc3VsdCA9IEV2
YWwuY29udGFpbnMoaW5wdXQsIGNvbXBhcmUpOwkKCVN0cmluZyBlbmRUaW1lID0gVXRpbC5nZXRU
aW1lU3RhbXAoKTsJCQoJCgkvLyBBZGQgdGVzdCByZXN1bHQgdG8gb3V0cHV0IGRvY3VtZW50CglJ
RGF0YVtdIG91dFJlc3VsdExpc3QgPSBidWlsZFRlc3RSZXN1bHRzKHBpcGVDdXJzb3IsIHJlc3Vs
dCwgaW5pdFRpbWUsIGVuZFRpbWUpOwoJCgkvLyBhZGQgdGhlIG91dHB1dERvYyB0byB0aGUgcGlw
ZWxpbmUKCUlEYXRhVXRpbC5wdXQocGlwZUN1cnNvciwgInJlc3VsdExpc3QiLCBvdXRSZXN1bHRM
aXN0KTsKCQp9IGZpbmFsbHkgewoJLy8gZGVzdHJveSB0aGUgcGlwZWxpbmVDdXJzb3IKCXBpcGVD
dXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
