<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">greatThan</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZUN1cnNvciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoKdHJ5IHsKCVN0
cmluZyBpbnB1dCA9IHBpcGVDdXJzb3IuZmlyc3QoImlucHV0IikgPyAoU3RyaW5nKXBpcGVDdXJz
b3IuZ2V0VmFsdWUoKSA6IG51bGw7CglTdHJpbmcgY29tcGFyZSA9IHBpcGVDdXJzb3IuZmlyc3Qo
ImNvbXBhcmUiKSA/IChTdHJpbmcpcGlwZUN1cnNvci5nZXRWYWx1ZSgpIDogbnVsbDsKCQoJU3Ry
aW5nIGluaXRUaW1lID0gVXRpbC5nZXRUaW1lU3RhbXAoKTsJCQoJUmVzdWx0IHJlc3VsdCA9IEV2
YWwuZ3JlYXRUaGFuKGlucHV0LCBjb21wYXJlKTsJCglTdHJpbmcgZW5kVGltZSA9IFV0aWwuZ2V0
VGltZVN0YW1wKCk7CQkKCQoJLy8gQWRkIHRlc3QgcmVzdWx0IHRvIG91dHB1dCBkb2N1bWVudAoJ
SURhdGFbXSBvdXRSZXN1bHRMaXN0ID0gYnVpbGRUZXN0UmVzdWx0cyhwaXBlQ3Vyc29yLCByZXN1
bHQsIGluaXRUaW1lLCBlbmRUaW1lKTsKCQoJLy8gYWRkIHRoZSBvdXRwdXREb2MgdG8gdGhlIHBp
cGVsaW5lCglJRGF0YVV0aWwucHV0KHBpcGVDdXJzb3IsICJyZXN1bHRMaXN0Iiwgb3V0UmVzdWx0
TGlzdCk7CgkKfSBmaW5hbGx5IHsKCS8vIGRlc3Ryb3kgdGhlIHBpcGVsaW5lQ3Vyc29yCglwaXBl
Q3Vyc29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
