<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">nvl</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7ClN0cmluZyBpbnB1dCA9
IGN1cnNvci5maXJzdCgiaW5wdXQiKSA/IChTdHJpbmcpY3Vyc29yLmdldFZhbHVlKCkgOiBudWxs
OwpTdHJpbmcgZGVmYXVsdFZhbHVlID0gY3Vyc29yLmZpcnN0KCJkZWZhdWx0IikgPyAoU3RyaW5n
KWN1cnNvci5nZXRWYWx1ZSgpIDogbnVsbDsKYm9vbGVhbiB0cmVhdEVtcHR5QXNOdWxsID0gY3Vy
c29yLmZpcnN0KCJ0cmVhdEVtcHR5QXNOdWxsIikgPyAoKEJvb2xlYW4pY3Vyc29yLmdldFZhbHVl
KCkpLyouZXF1YWxzKCJ0cnVlIikqLyA6IGZhbHNlOwoKY3Vyc29yLmluc2VydEFmdGVyKCJ2YWx1
ZSIsIFV0aWwubnZsKGlucHV0LCBkZWZhdWx0VmFsdWUsIHRyZWF0RW1wdHlBc051bGwpKTsKY3Vy
c29yLmluc2VydEFmdGVyKCJwYXJhbXMiLCAiaW5wdXRbIiArIGlucHV0ICsgIl0gZGVmYXVsdFZh
bHVlWyIgKyBkZWZhdWx0VmFsdWUgKyAiXSB0cmVhdEVtcHR5QXNOdWxsWyIgKyB0cmVhdEVtcHR5
QXNOdWxsICsgIl0iKTsKCmN1cnNvci5kZXN0cm95KCk7</value>
</Values>
