<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">lessThanEqual</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZUN1cnNvciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoKdHJ5IHsKCVN0
cmluZyBpbnB1dCA9IHBpcGVDdXJzb3IuZmlyc3QoImlucHV0IikgPyAoU3RyaW5nKXBpcGVDdXJz
b3IuZ2V0VmFsdWUoKSA6IG51bGw7CglTdHJpbmcgY29tcGFyZSA9IHBpcGVDdXJzb3IuZmlyc3Qo
ImNvbXBhcmUiKSA/IChTdHJpbmcpcGlwZUN1cnNvci5nZXRWYWx1ZSgpIDogbnVsbDsKCQoJU3Ry
aW5nIGluaXRUaW1lID0gVXRpbC5nZXRUaW1lU3RhbXAoKTsJCQoJUmVzdWx0IHJlc3VsdCA9IEV2
YWwubGVzc1RoYW5FcXVhbChpbnB1dCwgY29tcGFyZSk7CQoJU3RyaW5nIGVuZFRpbWUgPSBVdGls
LmdldFRpbWVTdGFtcCgpOwkJCgkKCS8vIEFkZCB0ZXN0IHJlc3VsdCB0byBvdXRwdXQgZG9jdW1l
bnQKCUlEYXRhW10gb3V0UmVzdWx0TGlzdCA9IGJ1aWxkVGVzdFJlc3VsdHMocGlwZUN1cnNvciwg
cmVzdWx0LCBpbml0VGltZSwgZW5kVGltZSk7CgkKCS8vIGFkZCB0aGUgb3V0cHV0RG9jIHRvIHRo
ZSBwaXBlbGluZQoJSURhdGFVdGlsLnB1dChwaXBlQ3Vyc29yLCAicmVzdWx0TGlzdCIsIG91dFJl
c3VsdExpc3QpOwoJCn0gZmluYWxseSB7CgkvLyBkZXN0cm95IHRoZSBwaXBlbGluZUN1cnNvcgoJ
cGlwZUN1cnNvci5kZXN0cm95KCk7Cn0=</value>
</Values>
