<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">greatThanEqual</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZUN1cnNvciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoKdHJ5IHsKCVN0
cmluZyBpbnB1dCA9IHBpcGVDdXJzb3IuZmlyc3QoImlucHV0IikgPyAoU3RyaW5nKXBpcGVDdXJz
b3IuZ2V0VmFsdWUoKSA6IG51bGw7CglTdHJpbmcgY29tcGFyZSA9IHBpcGVDdXJzb3IuZmlyc3Qo
ImNvbXBhcmUiKSA/IChTdHJpbmcpcGlwZUN1cnNvci5nZXRWYWx1ZSgpIDogbnVsbDsKCQoJU3Ry
aW5nIGluaXRUaW1lID0gVXRpbC5nZXRUaW1lU3RhbXAoKTsJCQoJUmVzdWx0IHJlc3VsdCA9IEV2
YWwuZ3JlYXRUaGFuRXF1YWwoaW5wdXQsIGNvbXBhcmUpOwkKCVN0cmluZyBlbmRUaW1lID0gVXRp
bC5nZXRUaW1lU3RhbXAoKTsJCQoJCgkvLyBBZGQgdGVzdCByZXN1bHQgdG8gb3V0cHV0IGRvY3Vt
ZW50CglJRGF0YVtdIG91dFJlc3VsdExpc3QgPSBidWlsZFRlc3RSZXN1bHRzKHBpcGVDdXJzb3Is
IHJlc3VsdCwgaW5pdFRpbWUsIGVuZFRpbWUpOwoJCgkvLyBhZGQgdGhlIG91dHB1dERvYyB0byB0
aGUgcGlwZWxpbmUKCUlEYXRhVXRpbC5wdXQocGlwZUN1cnNvciwgInJlc3VsdExpc3QiLCBvdXRS
ZXN1bHRMaXN0KTsKCQp9IGZpbmFsbHkgewoJLy8gZGVzdHJveSB0aGUgcGlwZWxpbmVDdXJzb3IK
CXBpcGVDdXJzb3IuZGVzdHJveSgpOwp9</value>
</Values>
