<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">decode</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZUN1cnNvciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoKdHJ5IHsKCVN0
cmluZyBpbnB1dCA9IHBpcGVDdXJzb3IuZmlyc3QoImlucHV0IikgPyAoU3RyaW5nKXBpcGVDdXJz
b3IuZ2V0VmFsdWUoKSA6IG51bGw7CglTdHJpbmcgY29tcGFyZSA9IHBpcGVDdXJzb3IuZmlyc3Qo
ImNvbXBhcmUiKSA/IChTdHJpbmcpcGlwZUN1cnNvci5nZXRWYWx1ZSgpIDogbnVsbDsKCVN0cmlu
Z1tdIGtleVBhaXJDb25kaXRpb25zID0gcGlwZUN1cnNvci5maXJzdCgia2V5UGFpckNvbmRpdGlv
bnMiKSA/IChTdHJpbmdbXSlwaXBlQ3Vyc29yLmdldFZhbHVlKCkgOiBudWxsOwoJCglTdHJpbmcg
aW5pdFRpbWUgPSBVdGlsLmdldFRpbWVTdGFtcCgpOwkJCglSZXN1bHQgcmVzdWx0ID0gRXZhbC5k
ZWNvZGUoaW5wdXQsIGNvbXBhcmUsIGtleVBhaXJDb25kaXRpb25zKTsJCglTdHJpbmcgZW5kVGlt
ZSA9IFV0aWwuZ2V0VGltZVN0YW1wKCk7CQkKCQoJLy8gQWRkIHRlc3QgcmVzdWx0IHRvIG91dHB1
dCBkb2N1bWVudAoJSURhdGFbXSBvdXRSZXN1bHRMaXN0ID0gYnVpbGRUZXN0UmVzdWx0cyhwaXBl
Q3Vyc29yLCByZXN1bHQsIGluaXRUaW1lLCBlbmRUaW1lKTsKCQoJLy8gYWRkIHRoZSBvdXRwdXRE
b2MgdG8gdGhlIHBpcGVsaW5lCglJRGF0YVV0aWwucHV0KHBpcGVDdXJzb3IsICJyZXN1bHRMaXN0
Iiwgb3V0UmVzdWx0TGlzdCk7CgkKfSBmaW5hbGx5IHsKCS8vIGRlc3Ryb3kgdGhlIHBpcGVsaW5l
Q3Vyc29yCglwaXBlQ3Vyc29yLmRlc3Ryb3koKTsKfQ==</value>
</Values>
